# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/138/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/138/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tristan/Desktop/gitHub/tetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tristan/Desktop/gitHub/tetris

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/138/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/138/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tristan/Desktop/gitHub/tetris/CMakeFiles /home/tristan/Desktop/gitHub/tetris/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tristan/Desktop/gitHub/tetris/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tetris

# Build rule for target.
tetris: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tetris
.PHONY : tetris

# fast build rule for target.
tetris/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/build
.PHONY : tetris/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tetris/falling.o: src/tetris/falling.cpp.o

.PHONY : src/tetris/falling.o

# target to build an object file
src/tetris/falling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetris/falling.cpp.o
.PHONY : src/tetris/falling.cpp.o

src/tetris/falling.i: src/tetris/falling.cpp.i

.PHONY : src/tetris/falling.i

# target to preprocess a source file
src/tetris/falling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetris/falling.cpp.i
.PHONY : src/tetris/falling.cpp.i

src/tetris/falling.s: src/tetris/falling.cpp.s

.PHONY : src/tetris/falling.s

# target to generate assembly for a file
src/tetris/falling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetris/falling.cpp.s
.PHONY : src/tetris/falling.cpp.s

src/tetris/shapes.o: src/tetris/shapes.cpp.o

.PHONY : src/tetris/shapes.o

# target to build an object file
src/tetris/shapes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetris/shapes.cpp.o
.PHONY : src/tetris/shapes.cpp.o

src/tetris/shapes.i: src/tetris/shapes.cpp.i

.PHONY : src/tetris/shapes.i

# target to preprocess a source file
src/tetris/shapes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetris/shapes.cpp.i
.PHONY : src/tetris/shapes.cpp.i

src/tetris/shapes.s: src/tetris/shapes.cpp.s

.PHONY : src/tetris/shapes.s

# target to generate assembly for a file
src/tetris/shapes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetris/shapes.cpp.s
.PHONY : src/tetris/shapes.cpp.s

src/tetris/types.o: src/tetris/types.cpp.o

.PHONY : src/tetris/types.o

# target to build an object file
src/tetris/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetris/types.cpp.o
.PHONY : src/tetris/types.cpp.o

src/tetris/types.i: src/tetris/types.cpp.i

.PHONY : src/tetris/types.i

# target to preprocess a source file
src/tetris/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetris/types.cpp.i
.PHONY : src/tetris/types.cpp.i

src/tetris/types.s: src/tetris/types.cpp.s

.PHONY : src/tetris/types.s

# target to generate assembly for a file
src/tetris/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tetris/types.cpp.s
.PHONY : src/tetris/types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tetris"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tetris/falling.o"
	@echo "... src/tetris/falling.i"
	@echo "... src/tetris/falling.s"
	@echo "... src/tetris/shapes.o"
	@echo "... src/tetris/shapes.i"
	@echo "... src/tetris/shapes.s"
	@echo "... src/tetris/types.o"
	@echo "... src/tetris/types.i"
	@echo "... src/tetris/types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

